import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

// Components
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

// Next Theme Provider
import  { NextThemeProvider } from '@/components/theme/ThemeProvider';



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        <NextThemeProvider attribute="class" defaultTheme="light">
          <Header />
            {children}
          <Footer /> 
        </NextThemeProvider>
      </body>
    </html>
  )
}
